# Simple feed forward neural network

I this notebook I train a simple feed forward neural network on some feature setups. Catalan languages.

In [1]:
import get_train_test
import feature_extraction

In [2]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD

/Users/indra/anaconda/envs/icutestenv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
from sklearn.preprocessing import LabelBinarizer
import numpy as np
from sklearn.metrics import confusion_matrix

#### BOW term frequencies + TF_IDF

In [4]:
X_train,y_train,X_test,y_test = feature_extraction.get_BOW_train_test_features(language="cat",k=1,repeat=True,tf_idf=True)

train on 2191 instances, test on 731 instances


In [5]:
encoder = LabelBinarizer()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [8]:
k = X_train.shape[1]+1
n = k*10**2

model = Sequential()
model.add(Dense(768, input_dim=4941, activation="relu", kernel_initializer="uniform"))
model.add(Dense(384, activation="relu", kernel_initializer="uniform"))
model.add(Dense(3))
model.add(Activation("softmax"))

model.compile(loss="binary_crossentropy", optimizer='Adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=128,verbose=1)


Epoch 1/20
2191/2191 [==============================] - 2s 1ms/step - loss: 0.5694 - acc: 0.6997
Epoch 2/20
2191/2191 [==============================] - 2s 809us/step - loss: 0.4026 - acc: 0.8328
Epoch 3/20
2191/2191 [==============================] - 2s 806us/step - loss: 0.2142 - acc: 0.9083
Epoch 4/20
2191/2191 [==============================] - 2s 1000us/step - loss: 0.1102 - acc: 0.9487
Epoch 5/20
2191/2191 [==============================] - 2s 846us/step - loss: 0.0424 - acc: 0.9977
Epoch 6/20
2191/2191 [==============================] - 2s 855us/step - loss: 0.0112 - acc: 0.9988
Epoch 7/20
2191/2191 [==============================] - 2s 862us/step - loss: 0.0039 - acc: 1.0000
Epoch 8/20
2191/2191 [==============================] - 2s 815us/step - loss: 0.0019 - acc: 1.0000
Epoch 9/20
2191/2191 [==============================] - 2s 811us/step - loss: 0.0013 - acc: 1.0000
Epoch 10/20
2191/2191 [==============================] - 2s 825us/step - loss: 0.0011 - acc: 1.0000
Epoch 11/2

In [96]:
y_pred = model.predict_classes(X_test)

In [97]:
test = []
for i in y_test:
    test.append(list(i).index(1))
test = np.array(test)    


In [98]:
np.mean(test == y_pred)

0.66484268125855

In [99]:
C = confusion_matrix(test, y_pred)
np.transpose( np.transpose(C) / C.astype(np.float).sum(axis=1) )

array([[0.76441103, 0.14035088, 0.0952381 ],
       [0.5045045 , 0.36936937, 0.12612613],
       [0.28054299, 0.08597285, 0.63348416]])

#### BOW term frequencies + TF_IDF, lemmatized


In [100]:
X_train,y_train,X_test,y_test = feature_extraction.get_LP_BOW_train_test_features(language="cat",k=1,repeat=True,tf_idf=True)

train on 2191 instances, test on 731 instances


In [102]:
encoder = LabelBinarizer()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [103]:
k = X_train.shape[1]+1
n = k*10**2

model = Sequential()
model.add(Dense(768, input_dim=3330, activation="relu", kernel_initializer="uniform"))
model.add(Dense(384, activation="relu", kernel_initializer="uniform"))
model.add(Dense(3))
model.add(Activation("softmax"))

model.compile(loss="binary_crossentropy", optimizer='Adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=128,verbose=1)

Epoch 1/20
2143/2143 [==============================] - 2s 1ms/step - loss: 0.5758 - acc: 0.6937
Epoch 2/20
2143/2143 [==============================] - 1s 663us/step - loss: 0.4397 - acc: 0.8062
Epoch 3/20
2143/2143 [==============================] - 1s 683us/step - loss: 0.2757 - acc: 0.8833
Epoch 4/20
2143/2143 [==============================] - 1s 666us/step - loss: 0.1630 - acc: 0.9216
Epoch 5/20
2143/2143 [==============================] - 1s 665us/step - loss: 0.0912 - acc: 0.9812
Epoch 6/20
2143/2143 [==============================] - 1s 652us/step - loss: 0.0446 - acc: 0.9911
Epoch 7/20
2143/2143 [==============================] - 1s 636us/step - loss: 0.0248 - acc: 0.9924
Epoch 8/20
2143/2143 [==============================] - 1s 678us/step - loss: 0.0215 - acc: 0.9927
Epoch 9/20
2143/2143 [==============================] - 2s 731us/step - loss: 0.0166 - acc: 0.9930
Epoch 10/20
2143/2143 [==============================] - 1s 688us/step - loss: 0.0178 - acc: 0.9932
Epoch 11/20

In [104]:
y_pred = model.predict_classes(X_test)
test = []
for i in y_test:
    test.append(list(i).index(1))
test = np.array(test)    
np.mean(test == y_pred)

0.6965034965034965

In [105]:
C = confusion_matrix(test, y_pred)
np.transpose( np.transpose(C) / C.astype(np.float).sum(axis=1) )

array([[0.83462532, 0.05684755, 0.10852713],
       [0.56074766, 0.29906542, 0.14018692],
       [0.26696833, 0.08597285, 0.64705882]])

#### Lemmatized BOW term frequencies + TF_IDF, 2-grams TF-IDF, 3-grams TF-IDF

In [107]:
X_train1,y_train,X_test1,y_test = feature_extraction.get_LP_BOW_train_test_features(language="cat",k=1,repeat=True,tf_idf=True)
X_train2,y_train,X_test2,y_test = feature_extraction.get_LP_ngram_train_test_features(language="cat",k=1,n=2,tf_idf=True)
X_train3,y_train,X_test3,y_test = feature_extraction.get_LP_ngram_train_test_features(language="cat",k=1,n=3,tf_idf=True)
X_train=np.concatenate((X_train1,X_train2,X_train3),axis=1)
X_test=np.concatenate((X_test1,X_test2,X_test3),axis=1)

train on 2191 instances, test on 731 instances
train on 2191 instances, test on 731 instances
train on 2191 instances, test on 731 instances


In [108]:
encoder = LabelBinarizer()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [110]:
k = X_train.shape[1]+1
n = k*10**2

model = Sequential()
model.add(Dense(768, input_dim=51465, activation="relu", kernel_initializer="uniform"))
model.add(Dense(384, activation="relu", kernel_initializer="uniform"))
model.add(Dense(3))
model.add(Activation("softmax"))

model.compile(loss="binary_crossentropy", optimizer='Adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=128,verbose=1)

Epoch 1/20
2143/2143 [==============================] - 24s 11ms/step - loss: 0.5710 - acc: 0.7038
Epoch 2/20
2143/2143 [==============================] - 21s 10ms/step - loss: 0.3145 - acc: 0.8698
Epoch 3/20
2143/2143 [==============================] - 22s 10ms/step - loss: 0.1272 - acc: 0.9375
Epoch 4/20
2143/2143 [==============================] - 18s 8ms/step - loss: 0.0640 - acc: 0.9891
Epoch 5/20
2143/2143 [==============================] - 16s 8ms/step - loss: 0.0251 - acc: 0.9932
Epoch 6/20
2143/2143 [==============================] - 16s 8ms/step - loss: 0.0189 - acc: 0.9938
Epoch 7/20
2143/2143 [==============================] - 17s 8ms/step - loss: 0.0179 - acc: 0.9941
Epoch 8/20
2143/2143 [==============================] - 16s 8ms/step - loss: 0.0165 - acc: 0.9935
Epoch 9/20
2143/2143 [==============================] - 18s 8ms/step - loss: 0.0172 - acc: 0.9944
Epoch 10/20
2143/2143 [==============================] - 20s 9ms/step - loss: 0.0120 - acc: 0.9946
Epoch 11/20
2143

In [111]:
y_pred = model.predict_classes(X_test)
test = []
for i in y_test:
    test.append(list(i).index(1))
test = np.array(test)    
np.mean(test == y_pred)

0.7104895104895105

In [112]:
C = confusion_matrix(test, y_pred)
np.transpose( np.transpose(C) / C.astype(np.float).sum(axis=1) )

array([[0.84237726, 0.08527132, 0.07235142],
       [0.45794393, 0.36448598, 0.17757009],
       [0.2760181 , 0.07692308, 0.64705882]])